name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  flutter-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

#      - uses: futureware-tech/simulator-action@v3
#        with:
#          model: 'iPhone 14'

#      - name: Setup Java
#        uses: actions/setup-java@v1
#        with:
#          java-version: '12.x'

      - name: Setup Flutter 3.22.3
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.22.3'

      - run: flutter pub get
#      - run: flutter test integration_test/tests/create_tests.dart

      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          profile: Nexus 6
          arch: arm64-v8a
          force-avd-creation: false
          avd-name: macOS-avd-arm64-v8a-31
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: flutter test integration_test/tests/create_tests.dart
