name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ios-flutter-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: futureware-tech/simulator-action@v3
        with:
          device: 'iPhone 14'

      - name: Setup Flutter 3.22.3
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.22.3'

      - run: flutter pub get
      - run: flutter test integration_test/tests/create_tests.dart

  android:
    runs-on: macos-13
#    strategy:
#      matrix:
#        api-level:
#          - 29
#          # you can add more API level if you want to run your tests on different API
#      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter 3.22.3
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.22.3'

      - name: flutter pub get
        run: flutter pub get

      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: flutter test integration_test/tests/create_tests.dart

#      # Build apk.
#      - run: flutter build apk
#
#        # Upload generated apk to the artifacts.
#      - uses: actions/upload-artifact@v1
#        with:
#          name: release-apk
#          path: build/app/outputs/apk/release/app-release.apk