name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  flutter-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [29]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

#      - uses: futureware-tech/simulator-action@v3
#        with:
#          model: 'iPhone 14'

      - name: "Run UI Tests"
        uses: vgaidarji/android-github-actions-emulator@v1.0.1

#      - name: Setup Java
#        uses: actions/setup-java@v1
#        with:
#          java-version: '12.x'

      - name: Setup Flutter 3.22.3
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.22.3'

      - run: flutter pub get
      - run: flutter test integration_test/tests/create_tests.dart